### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by shokre** [hrvach/OraoPy#3]
Hi,

I've been toying around with creating [cc65 runtime for Orao](https://github.com/shokre/orao-cc65).

In the process I've [forked](https://github.com/shokre/OraoPy) this emulator, and added following features (useful for development):
- support for loading `.prg` binaries generated by cc65
- development UI

Could you please add a LICENSE file to your project, so that I can fork under proper rules?

Thanks

**Comment by hrvach** [comment]
Absolutely, added. I have to check your project, that's a pretty cool idea! :)

**Comment by shokre** [comment]
Thanks!

I've merged your LICENSE with my project
